name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run App
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run start &

    - name: Run E2E Tests
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm run e2e
