name: Node.js CI

on: [push]

jobs:
  e2e:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run App
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run start &

    - name: Run E2E Tests
      uses: microsoft/playwright-github-action@v1
    - run: npm run e2e
