name: Node.js CI

on: [push]

jobs:
  e2e:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run start &
    - run: npx playwright install-deps
    - run: npm run e2e
